apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      # Derived Fields extract structured data from log lines and turn them
      # into clickable links. Here we extract trace_id from the JSON log
      # and create a link. In Lab 04 (prod) this will link to Tempo.
      # In this lab it just shows the trace_id is present and parseable.
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":"(\w+)"'
          url: ""
          urlDisplayLabel: "trace_id"
